# Runs on the HOST machine (initializeCommand) before the devcontainer is created.
# Windows fallback for configure-git-mounts.sh — generates .devcontainer/docker-compose.yaml.
#
# Used automatically when bash is not available on the host (Windows without WSL bash).
# The initializeCommand runs: bash configure-git-mounts.sh || powershell configure-git-mounts.ps1

$ErrorActionPreference = 'Stop'

$localWorkspace = (Get-Location).Path -replace '\\', '/'
$workspaceName = Split-Path -Leaf (Get-Location)
$workspaceNameLower = $workspaceName.ToLower()
$containerWorkspace = "/workspaces/$workspaceName"

# Resolve the absolute path to the main repo's .git directory.
# git-common-dir returns ".git" (relative) for the main repo and an absolute path
# for a linked worktree — both let us derive the main repo name without --show-toplevel,
# which incorrectly returns the worktree root instead of the main repo root.
$gitCommonDirRaw = git rev-parse --git-common-dir 2>$null
if (-not $gitCommonDirRaw) { $gitCommonDirRaw = '.git' }
if (-not [System.IO.Path]::IsPathRooted($gitCommonDirRaw)) {
    $gitCommonDirRaw = Join-Path (Get-Location) $gitCommonDirRaw
}
$gitCommonDirAbs = $gitCommonDirRaw -replace '\\', '/'
$mainRepoName = (Split-Path -Leaf (Split-Path -Parent $gitCommonDirRaw)).ToLower()

$gitVolumeLine = ''
$gitPath = Join-Path (Get-Location) '.git'

if (Test-Path $gitPath -PathType Leaf) {
    $gitVolumeLine = "      - ${gitCommonDirAbs}:/git-root"
    Write-Host "[configure-git-mounts] Linked worktree -- mounting git root at /git-root"
    Write-Host "[configure-git-mounts]   source: $gitCommonDirAbs"
} else {
    Write-Host '[configure-git-mounts] Main repository -- no extra git mount needed'
}

$lines = @(
    '# Generated by .devcontainer/configure-git-mounts.ps1 -- do not edit by hand.'
    '# Re-generated each time VS Code opens this folder in a devcontainer.'
    'services:'
    '  devcontainer:'
    '    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04'
    '    command: sleep infinity'
    '    volumes:'
    "      - ${localWorkspace}:${containerWorkspace}"
    "      - node-modules:${containerWorkspace}/frontend/node_modules"
    '      - claude-config:/home/vscode/.claude'
)
if ($gitVolumeLine) { $lines += $gitVolumeLine }
$lines += @(
    ''
    'volumes:'
    '  node-modules:'
    "    name: ${workspaceNameLower}-frontend-node-modules"
    '  claude-config:'
    "    name: ${mainRepoName}-claude-config"
    ''
)

$outputPath = [System.IO.Path]::GetFullPath('.devcontainer/docker-compose.yaml')
$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outputPath, ($lines -join "`n"), $encoding)

Write-Host '[configure-git-mounts] Wrote .devcontainer/docker-compose.yaml'
