# Runs on the HOST machine (initializeCommand) before the devcontainer is created.
# Windows fallback for configure-git-mounts.sh — generates .devcontainer/docker-compose.yaml.
#
# Used automatically when bash is not available on the host (Windows without WSL bash).
# The initializeCommand runs: bash configure-git-mounts.sh || powershell configure-git-mounts.ps1

$ErrorActionPreference = 'Stop'

$localWorkspace = (Get-Location).Path -replace '\\', '/'
$workspaceName = Split-Path -Leaf (Get-Location)
$workspaceNameLower = $workspaceName.ToLower()
# Use lowercase so the container path matches ${localWorkspaceFolderBasename} which VS Code
# derives from the CLI arg (case-insensitive on Windows, but case-sensitive on Linux).
$containerWorkspace = "/workspaces/$workspaceNameLower"

$gitVolumeLine = ''
$gitPath = Join-Path (Get-Location) '.git'

if (Test-Path $gitPath -PathType Leaf) {
    # Linked worktree: the main repo is always 3 levels up (.claude/worktrees/<name>).
    # Navigate up directly — do not use git rev-parse, which fails if git metadata is stale
    # and whose errors cannot be cleanly suppressed in Windows PowerShell 5.1.
    $mainRepoPath = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Get-Location)))
    $mainGitDir = Join-Path $mainRepoPath '.git'
    if (Test-Path $mainGitDir -PathType Container) {
        $mainGitDirFwd = $mainGitDir -replace '\\', '/'
        $gitVolumeLine = "      - ${mainGitDirFwd}:/git-root"
        $mainRepoName = (Split-Path -Leaf $mainRepoPath).ToLower()
        Write-Host "[configure-git-mounts] Linked worktree -- mounting git root at /git-root"
        Write-Host "[configure-git-mounts]   source: $mainGitDirFwd"
    } else {
        $mainRepoName = $workspaceNameLower
        Write-Host "[configure-git-mounts] WARNING: expected main repo .git not found at: $mainGitDir"
        Write-Host "[configure-git-mounts]   Worktree must be 3 levels deep under the main repo (.claude/worktrees/<name>)"
    }
} else {
    $mainRepoName = $workspaceNameLower
    Write-Host '[configure-git-mounts] Main repository -- no extra git mount needed'
}

$lines = @(
    '# Generated by .devcontainer/configure-git-mounts.ps1 -- do not edit by hand.'
    '# Re-generated each time VS Code opens this folder in a devcontainer.'
    '#'
    '# VS Code pulls ghcr.io/piers-sinclair/dostar-devcontainer:latest on every'
    '# new container create. The image must be public (or docker login ghcr.io done first).'
    '# To test locally before the image is published:'
    '#   docker build -t ghcr.io/piers-sinclair/dostar-devcontainer:latest -f .devcontainer/Dockerfile .'
    'services:'
    '  devcontainer:'
    '    image: ghcr.io/piers-sinclair/dostar-devcontainer:latest'
    '    command: sleep infinity'
    '    volumes:'
    "      - ${localWorkspace}:${containerWorkspace}"
    "      - node-modules:${containerWorkspace}/frontend/node_modules"
    '      - claude-config:/home/vscode/.claude'
    '      - playwright-cache:/home/vscode/.cache/ms-playwright'
    '      - pnpm-store:/usr/local/pnpm-store'
    '      - nuget-packages:/home/vscode/.nuget/packages'
    '      - /var/run/docker.sock:/var/run/docker.sock'
)
if ($gitVolumeLine) { $lines += $gitVolumeLine }
$lines += @(
    ''
    'volumes:'
    '  node-modules:'
    "    name: ${workspaceNameLower}-frontend-node-modules"
    '  claude-config:'
    "    name: ${mainRepoName}-claude-config"
    '  playwright-cache:'
    "    name: dostar-playwright-cache"
    '  pnpm-store:'
    "    name: dostar-pnpm-store"
    '  nuget-packages:'
    "    name: dostar-nuget-packages"
    ''
)

$outputPath = [System.IO.Path]::GetFullPath('.devcontainer/docker-compose.yaml')
$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outputPath, ($lines -join "`n"), $encoding)

Write-Host '[configure-git-mounts] Wrote .devcontainer/docker-compose.yaml'
