# Runs on the HOST machine (initializeCommand) before the devcontainer is created.
# Windows version of configure-git-mounts.sh — generates .devcontainer/docker-compose.yaml.
#
# For linked worktrees: mounts the main repo's .git directory at /git-root inside
# the container. postCreate.sh then rewrites the .git pointer to /git-root/worktrees/<name>.

$ErrorActionPreference = 'Stop'

$workspaceName = Split-Path -Leaf (Get-Location)
$containerWorkspace = "/workspaces/$workspaceName"

$toplevel = git rev-parse --show-toplevel 2>$null
if (-not $toplevel) { $toplevel = (Get-Location).Path }
$mainRepoName = (Split-Path -Leaf $toplevel).ToLower()

$gitVolumeLine = ''
$gitPath = Join-Path (Get-Location) '.git'

if (Test-Path $gitPath -PathType Leaf) {
    # Linked worktree: .git is a file pointing to the main repo's git directory.
    $gitCommonDir = git rev-parse --git-common-dir
    if (-not [System.IO.Path]::IsPathRooted($gitCommonDir)) {
        $gitCommonDir = Join-Path (Get-Location) $gitCommonDir
    }
    # Docker Compose volume paths on Windows use forward slashes (C:/repos/...).
    $gitCommonDirFwd = $gitCommonDir -replace '\\', '/'
    $gitVolumeLine = "      - ${gitCommonDirFwd}:/git-root"
    Write-Host "[configure-git-mounts] Linked worktree -- mounting git root at /git-root"
    Write-Host "[configure-git-mounts]   source: $gitCommonDir"
} else {
    Write-Host '[configure-git-mounts] Main repository -- no extra git mount needed'
}

$lines = @(
    '# Generated by .devcontainer/configure-git-mounts.ps1 -- do not edit by hand.'
    '# Re-generated each time VS Code opens this folder in a devcontainer.'
    'services:'
    '  devcontainer:'
    '    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04'
    '    command: sleep infinity'
    '    volumes:'
    "      - node-modules:${containerWorkspace}/frontend/node_modules"
    '      - claude-config:/home/vscode/.claude'
)
if ($gitVolumeLine) { $lines += $gitVolumeLine }
$lines += @(
    ''
    'volumes:'
    '  node-modules:'
    "    name: ${mainRepoName}-frontend-node-modules"
    '  claude-config:'
    "    name: ${mainRepoName}-claude-config"
    ''
)

# Write with LF line endings and no BOM so Docker Compose (Linux) reads it cleanly.
$outputPath = [System.IO.Path]::GetFullPath('.devcontainer/docker-compose.yaml')
$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outputPath, ($lines -join "`n"), $encoding)

Write-Host '[configure-git-mounts] Wrote .devcontainer/docker-compose.yaml'
