#!/bin/bash
# Runs on the HOST machine (initializeCommand) before the devcontainer is created.
#
# Generates .devcontainer/docker-compose.yaml with volume mounts tailored to whether
# this workspace is the main repository or a linked git worktree.
#
# Problem: a worktree's .git file contains an absolute host path. That path does not
# exist inside the container unless we explicitly bind-mount it.
#
# Solution: detect if we are in a worktree (.git is a file, not a directory), navigate
# 3 levels up to the main repo (convention: .claude/worktrees/<name>), and bind-mount
# the main repo's .git directory at /git-root. postCreate.sh then creates a /.git
# symlink so the existing relative .git pointer resolves correctly in both environments.

set -e

local_workspace="$(pwd)"
workspace_name=$(basename "$local_workspace")
workspace_name_lower=$(echo "$workspace_name" | tr '[:upper:]' '[:lower:]')
# Use lowercase so the container path matches ${localWorkspaceFolderBasename} which VS Code
# derives from the CLI arg (case-insensitive on Windows, but case-sensitive on Linux).
container_workspace="/workspaces/${workspace_name_lower}"

git_volume_line=""

if [ -f ".git" ]; then
    # Linked worktree: the main repo is always 3 levels up (.claude/worktrees/<name>).
    # Navigate up directly — do not use git rev-parse, which fails if git metadata is stale.
    main_repo_path="$(dirname "$(dirname "$(dirname "$local_workspace")")")"
    main_git_dir="${main_repo_path}/.git"
    if [ -d "$main_git_dir" ]; then
        git_volume_line="      - ${main_git_dir}:/git-root"
        main_repo_name=$(basename "$main_repo_path" | tr '[:upper:]' '[:lower:]')
        echo "[configure-git-mounts] Linked worktree — mounting git root at /git-root"
        echo "[configure-git-mounts]   source: ${main_git_dir}"
    else
        main_repo_name="$workspace_name_lower"
        echo "[configure-git-mounts] WARNING: expected main repo .git not found at: ${main_git_dir}"
        echo "[configure-git-mounts]   Worktree must be 3 levels deep under the main repo (.claude/worktrees/<name>)"
    fi
else
    main_repo_name="$workspace_name_lower"
    echo "[configure-git-mounts] Main repository — no extra git mount needed"
fi

cat > .devcontainer/docker-compose.yaml << YAML
# Generated by .devcontainer/configure-git-mounts.sh — do not edit by hand.
# Re-generated each time VS Code opens this folder in a devcontainer.
#
# VS Code pulls ghcr.io/piers-sinclair/dostar-devcontainer:latest on every
# new container create. The image must be public (or docker login ghcr.io done first).
# To test locally before the image is published:
#   docker build -t ghcr.io/piers-sinclair/dostar-devcontainer:latest -f .devcontainer/Dockerfile .
services:
  devcontainer:
    image: ghcr.io/piers-sinclair/dostar-devcontainer:latest
    command: sleep infinity
    volumes:
      - ${local_workspace}:${container_workspace}
      - node-modules:${container_workspace}/frontend/node_modules
      - claude-config:/home/vscode/.claude
      - playwright-cache:/home/vscode/.cache/ms-playwright
      - pnpm-store:/usr/local/pnpm-store
      - nuget-packages:/home/vscode/.nuget/packages
      - /var/run/docker.sock:/var/run/docker.sock
${git_volume_line}

volumes:
  node-modules:
    name: ${workspace_name_lower}-frontend-node-modules
  claude-config:
    name: ${main_repo_name}-claude-config
  playwright-cache:
    name: dostar-playwright-cache
  pnpm-store:
    name: dostar-pnpm-store
  nuget-packages:
    name: dostar-nuget-packages
YAML

echo "[configure-git-mounts] Wrote .devcontainer/docker-compose.yaml"
