name: Infra — spin up

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    uses: ./.github/workflows/infra-deploy.yml
    secrets: inherit

  bootstrap-rbac:
    needs: deploy-infra
    uses: ./.github/workflows/infra-bootstrap-rbac.yml
    secrets: inherit

  deploy-backend:
    needs: bootstrap-rbac
    uses: ./.github/workflows/cd-backend.yml
    secrets: inherit

  deploy-frontend:
    needs: deploy-backend
    uses: ./.github/workflows/cd-frontend.yml
    secrets: inherit
